const films = [
  { id: 1, titre: "Avengers" },
  { id: 2, titre: "Cyberpunk 2029" },
  { id: 3, titre: "Made in Abyss" },
  { id: 4, titre: "Demon Slayer" },
  { id: 5, titre: "Inception" },
  { id: 6, titre: "Interstellar" },
  { id: 7, titre: "The Dark Knight" },
  { id: 8, titre: "Gladiator" },
  { id: 9, titre: "Matrix" },
  { id: 10, titre: "Avatar: La Voie de l'eau" },
  { id: 11, titre: "Parasite" },
  { id: 12, titre: "Old Boy" },
  { id: 13, titre: "Train to Busan" },
  { id: 14, titre: "The Host" },
  { id: 15, titre: "Memories of Murder" },
  { id: 16, titre: "Decision to Leave" },
  { id: 17, titre: "La Noire de..." },
  { id: 18, titre: "Touki Bouki" },
  { id: 19, titre: "Atlantique" },
  { id: 20, titre: "Félicité" },
  { id: 21, titre: "Saloum" },
  { id: 22, titre: "Xalé, les promesses" },
  { id: 23, titre: "Moolaadé" },
  { id: 24, titre: "Viva Riva!" },
  { id: 25, titre: "La Vie est Belle" },
  { id: 26, titre: "Maki'la" },
  { id: 27, titre: "Augure" },
  { id: 28, titre: "Heart of Africa" },
  { id: 29, titre: "Tango Negro" },
  { id: 30, titre: "Juwaa" }
];

export default films;